In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


url = "https://raw.githubusercontent.com/aimlcommunity/Breast-Cancer-Detection-using-Machine-Learning/master/cancer%20dataset.csv"

data = pd.read_csv(url)

In [3]:
from sklearn.preprocessing import LabelEncoder
labelencoder_Y=LabelEncoder()
data.iloc[:,1]=labelencoder_Y.fit_transform(data.iloc[:,1].values)


In [5]:
X=data.iloc[:,2:31].values 
Y=data.iloc[:,1].values

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split(X,Y, test_size=0.25, random_state=0)


from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

# Logistic Regression : 

In [8]:
def logreg(X_train,Y_train):
    from sklearn.linear_model import LogisticRegression
    log=LogisticRegression(random_state=0)
    log.fit(X_train,Y_train)
    print("Logistic Regression Training accuracy",log.score(X_train,Y_train))
    return log


In [9]:
logrex=logreg(X_train,Y_train)

C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Logistic Regression Training accuracy 0.9906103286384976


In [10]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,logrex.predict(X_test))
print(cm)

[[86  4]
 [ 3 50]]


In [11]:
TP=cm[0][0]
TN=cm[1][1]
FN=cm[1][0]
FP=cm[0][1]
print("Testing accuracy of logistic regression model=", (TP+TN)/(TP+TN+FN+FP))

Testing accuracy of logistic regression model= 0.951048951048951


# Decision Tree Classifier : -

In [18]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
clf = DecisionTreeClassifier()
clf = clf.fit(X_train,Y_train)
Y_pred = clf.predict(X_test)

In [19]:
print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred))

Accuracy: 0.9090909090909091


In [20]:
cm1= confusion_matrix(Y_test,Y_pred)
print(cm1)

[[79 11]
 [ 2 51]]


In [29]:
TP=cm1[0][0]
TN=cm1[1][1]
FN=cm1[1][0]
FP=cm1[0][1]
print("Testing accuracy of Decision Tree Classifier model=", (TP+TN)/(TP+TN+FN+FP))

Testing accuracy of Decision Tree Classifier model= 0.9090909090909091


# Random Forest : -

In [22]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=100)
clf.fit(X_train,Y_train)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [24]:
Y_pred=clf.predict(X_test)

In [25]:
print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred))

Accuracy: 0.972027972027972


In [27]:
cm2=confusion_matrix(Y_test,Y_pred)
print(cm2)

[[87  3]
 [ 1 52]]


In [28]:
TP=cm2[0][0]
TN=cm2[1][1]
FN=cm2[1][0]
FP=cm2[0][1]
print("Testing accuracy of Random Forest Classifier model=", (TP+TN)/(TP+TN+FN+FP))

Testing accuracy of Random Forest Classifier model= 0.972027972027972


Random Forest has highest accuracy rate because multiple individual tests are done by individual tress which gave more accuracy.